version: "3.8"

services:
  redis:
    image: redis:7
    container_name: redis-bot
    ports:
      - "6379:6379"
    environment:
      - TZ=Europe/Moscow
    restart: unless-stopped
    volumes:
      - redis_data:/data

  tg-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tg-helper-bot
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      - TZ=Europe/Moscow
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    working_dir: /app
    command: ["python", "main.py"]

volumes:
  redis_data:
